<a href="https://colab.research.google.com/github/NehalPisalkar/Nehal2025/blob/main/(BASICS_OF_PANDAS)2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
import pandas as pd
import numpy as np

In [70]:
marks_1 = {
    'maths':67,
    'english':57,
    'science':89,
    'hindi':100
}

marks_series = pd.Series(marks_1,name='nitish ke marks')
marks_series

maths       67
english     57
science     89
hindi      100
Name: nitish ke marks, dtype: int64

In [71]:
marks_2 = {
    'maths':67,
    'english':57,
    'science':np.nan,
    'hindi':100
}

marks_series_2 = pd.Series(marks_2,name='nitish ke marks')
marks_series_2

maths       67.0
english     57.0
science      NaN
hindi      100.0
Name: nitish ke marks, dtype: float64

In [72]:
a = pd.read_csv(r'/content/bollywood.csv',index_col="movie")
a

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

In [73]:
b = pd.read_csv(r'/content/kohli_ipl.csv')

In [74]:
b.sort_values(ascending=False,by='runs')

     match_no  runs
127       128   113
125       126   109
122       123   108
119       120   100
163       164   100
..        ...   ...
92         93     0
129       130     0
205       206     0
206       207     0
210       211     0

[215 rows x 2 columns]

In [75]:
b.sort_values(inplace=True, by='runs')
b

     match_no  runs
7           8     0
86         87     0
92         93     0
90         91     0
205       206     0
..        ...   ...
163       164   100
119       120   100
122       123   108
125       126   109
127       128   113

[215 rows x 2 columns]

In [76]:
b.count()

match_no    215
runs        215
dtype: int64

In [77]:
b.sum()

match_no    23220
runs         6634
dtype: int64

In [78]:
b.describe()

         match_no        runs
count  215.000000  215.000000
mean   108.000000   30.855814
std     62.209324   26.229801
min      1.000000    0.000000
25%     54.500000    9.000000
50%    108.000000   24.000000
75%    161.500000   48.000000
max    215.000000  113.000000

In [79]:
b.median()

match_no    108.0
runs         24.0
dtype: float64

In [80]:
b.max()

match_no    215
runs        113
dtype: int64

In [81]:
x = pd.Series([12,13,14,35,46,57,58,79,9])
x

0    12
1    13
2    14
3    35
4    46
5    57
6    58
7    79
8     9
dtype: int64

In [82]:
b[5:16]

     match_no  runs
206       207     0
134       135     0
129       130     0
210       211     0
105       106     1
203       204     1
112       113     1
76         77     1
0           1     1
4           5     1
74         75     1

In [83]:
a[::2]

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
The Accidental Prime Minister (film)       Anupam Kher
Evening Shadows                       Mona Ambegaonkar
Fraud Saiyaan                             Arshad Warsi
Manikarnika: The Queen of Jhansi        Kangana Ranaut
...                                                ...
Raaz (2002 film)                            Dino Morea
Waisa Bhi Hota Hai Part II                Arshad Warsi
Kaante                                Amitabh Bachchan
Aankhen (2002 film)                   Amitabh Bachchan
Company (film)                              Ajay Devgn

[750 rows x 1 columns]

In [84]:
mean = b.mean()
median=b.median()
mode=b.mode()
std=b.std()
var=b.var()
print('mean: ',mean , '\nmedian',median, '\nmode:',mode, '\nstd:',std,'\nvar:',var)

mean:  match_no    108.000000
runs         30.855814
dtype: float64
median match_no    108.0
runs         24.0
dtype: float64
mode:      match_no  runs
0           1   0.0
1           2   NaN
2           3   NaN
3           4   NaN
4           5   NaN
..        ...   ...
210       211   NaN
211       212   NaN
212       213   NaN
213       214   NaN
214       215   NaN

[215 rows x 2 columns]
std: match_no    62.209324
runs        26.229801
dtype: float64
var: match_no    3870.000000
runs         688.002478
dtype: float64

In [85]:
marks_series

maths       67
english     57
science     89
hindi      100
Name: nitish ke marks, dtype: int64

In [86]:
marks_series[0:2]=100
marks_series[2:4]=50
marks_series

maths      100
english    100
science     50
hindi       50
Name: nitish ke marks, dtype: int64

In [87]:
marks_series['evs']=100
marks_series

maths      100
english    100
science     50
hindi       50
evs        100
Name: nitish ke marks, dtype: int64

In [90]:
runs = [13,24,56,78,100]

runs_ser = pd.Series(runs)
runs_ser

0     13
1     24
2     56
3     78
4    100
dtype: int64

In [91]:
runs_ser[[0,3,4]] = [0,0,0]
runs_ser

0     0
1    24
2    56
3     0
4     0
dtype: int64

In [92]:
print(len(runs_ser))

5

In [93]:
print(type(runs_ser))

<class 'pandas.core.series.Series'>